name: CI

on: push

jobs:
  specs-and-rubocop:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
        gemfile:
          - rails4.2
          - rails5.0
          - rails5.1
          - rails5.2
        task:
          - rspec
        exclude:
          - ruby-version: '2.7'
            gemfile: rails4.2
          - ruby-version: '3.0'
            gemfile: rails4.2
        include:
          - ruby-version: '2.5'
            gemfile: rails5.2
            task: rubocop
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: zendesk/checkout@v2
      - name: Set up Ruby
        uses: zendesk/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: ${{ matrix.task }}
        run: bundle exec ${{ matrix.task }}
